<!-- Below are examples, that illustrate the JavaScript Errors Throw and Try to Catch:

 -->
 <script>
    try {
	dadalert("Welcome Fellow Geek!");
}
catch (err) {
	console.log(err);
}

 </script>


<script>
    function geekFunc() {
	let a = 10;
	try {
		console.log("Value of variable a is : " + a);
	}
	catch (e) {
		console.log("Error: " + e.description);
	}
}
geekFunc();

</script>

<!-- Example: In this example, we will see the usage of try-catch block in javascript.

 -->

 <script>
    try {
	dadalert("Welcome Fellow Geek!");
}
catch (err) {
	console.log(err);
}

 </script>

 <!-- Example: In this example, we will see how a throw statement is used to throw an error in javascript.

 -->

 <script>
    try {
	throw new Error('Yeah... Sorry');
}
catch (e) {
	console.log(e);
}

 </script>

<!-- Example: In this example, we will learn about the final statement of Javascript.

 -->

 <script>
    try {
	console.log('try');
} catch (e) {
	console.log('catch');
} finally {
	console.log('finally');
}

 </script>